language: python
python:
- '3.7'
sudo: required
install:
- pip install flask
script:
- python test.py
deploy:
  provider: heroku
  app: devops-4linux-jean
  api_key:
    secure: Ft0jPbTE579GEHN6KiNG16L2wOYQ/V01MvmoM/+BIxgGJPbP8374zDM54gUm3uMTbj7QOW3dwi32o7PU5lAAetZegoZ4CvalfifpdwdaQfBUD2JKmhv8QiNIrnovgkthtIXBTvPHSordzYXVwe1obkWLMCTdQttP0h7X5dq7o0HlwZIVV0OVkh71hZ58RmJK87C5UQ06DFC/7AlHRncJql3h73Kz1dTtEWTvS5+6Mi1JUIwrxQYUMXj7Pwg/RcmMJoTemc0nVSTJcTj+hJF41ZTSVzAR2qS0ldwQLVKxd6R6BLCmoHuvYLauAsElhQTocJEfJNJhB1ClThaYq+Fkkm/y9Pj1NA85insRAm185s4Bm+N3U5eeHha+sScsdZAPqR3/XBpQVbqtz9OziFBNiEsOukE629WM0EBrrx1NKDZek7ym68unRImkmA8OYyjZYwq6f73G5iQT16aFQX0QtIA+3lDCNMW6jS9hDQS2qmlBx5ajxov8sTZN8t3rNs4Fz2jJwDF84hRWtzIyr5V7SNXQtDHTXJDIaG1DmCp/MLAnxD4CRjjFpoWAHVTAiOMjN9Oaj9nBzRVFtXrZgnUcozz4oohgV0H5A/iDS3cXCz4Azb5BVNyRi50kGXp10Xg/4YZpLvojdppv24f0BCpYPl8gYRZ9+BVAJn//L+aaA+I=
